version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    restart: always